# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Life Explorer
email: wongwy93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jotting down my code learning experience and tools I have used. Big :heart: of Nasi Lemak.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ikanyu.github.io/" # the base hostname & protocol for your site
twitter_username: wwy93
github_username:  ikanyu

# Build settings
markdown: kramdown
gems:
  - jemoji